silverorange/store

Store/admin/components/SalesByRegionReport/Details.php
Store/admin/components/SalesByRegionReport/Index.php
Store/admin/components/SalesByRegionReport/details.xml
Store/admin/components/SalesByRegionReport/include/StoreSalesByRegionGroup.php
Store/admin/components/SalesByRegionReport/index.xml

https://www.pivotaltracker.com/story/show/92053870

Add admin report for Sales by Country/Provstate

---

Store/Store.php

https://www.pivotaltracker.com/n/projects/1180016/stories/104560736

Push Authorize.net config to Store package.

---

Store/Store.php
Store/StoreAuthorizeNetPaymentProvider.php
Store/StoreBraintreePaymentProvider.php
Store/StorePayPalPaymentProvider.php
Store/StorePaymentProvider.php
Store/exceptions/StorePaymentBraintreeException.php
Store/pages/StoreCheckoutConfirmationPage.php
package.php

https://www.pivotaltracker.com/story/show/104033688

Braintree payments support

---

Store/StoreApplication.php

If the ini ever defines it outside `/account` this will ensure it works only on HTTPS.

Add account login page to the secure list.

---

Store/StoreAnalyticsOrderTracker.php
package.php

Requires https://github.com/silverorange/site/pull/151

Add support for Bing Universal Event Tracker to StoreAnalyticsOrderTracker.

---

Store/StoreAnalyticsOrderTracker.php

Requires https://github.com/silverorange/site/pull/154

Add twitter tracking to analytics

---

www/admin/styles/store-product-details-page.css
www/admin/styles/store-product-edit-page.css
www/styles/search-disclosure.css
www/styles/store-cart-lightbox.css
www/styles/store-checkout-progress.css
www/styles/store-feature-pager.css
www/styles/store-feedback-panel.css
www/styles/store-product-image-display.css
www/styles/store-product-page.css

Depends on:
https://github.com/silverorange/swat/pull/58
https://github.com/silverorange/admin/pull/48
https://github.com/silverorange/site/pull/162
https://github.com/silverorange/academy/pull/182
https://github.com/silverorange/Cme/pull/68

Remove obsolete browser hacks

---

Store/StoreCartLightbox.php

https://trello.com/c/mjUsCauI/670-php-5-6-array-to-string-ocnversion-on-cart-lightbox

Fix array-to-string conversion.

---

Store/pages/StoreProductPage.php

Note that the `$status` variable isn't used anywhere and I've removed it

Make it easier to subclass after cart entries are added

---

Store/dataobjects/StoreAccount.php
composer.json

The composer.json needs to be updated to depend on silverorange/swat#61.
https://hippoeducation.tpondemand.com/entity/293

Move company and phone behind getters and setters

---

Store/admin/components/Attribute/Edit.php
Store/admin/components/AttributeType/Edit.php
Store/admin/components/Catalog/Edit.php
Store/admin/components/Category/Edit.php
Store/admin/components/Category/ImageEdit.php
Store/admin/components/Feature/Edit.php
Store/admin/components/Item/Edit.php
Store/admin/components/ItemGroup/Edit.php
Store/admin/components/ItemMinimumQuantityGroup/Edit.php
Store/admin/components/Order/CommentEdit.php
Store/admin/components/Order/NoteEdit.php
Store/admin/components/PaymentType/Edit.php
Store/admin/components/PriceRange/Edit.php
Store/admin/components/Product/Edit.php
Store/admin/components/Product/ImageEdit.php
Store/admin/components/ProductReview/Edit.php
Store/admin/components/ProvState/Edit.php
Store/admin/components/Region/Edit.php
Store/admin/components/SaleDiscount/Edit.php
Store/admin/components/ShippingType/Edit.php
Store/admin/components/ShippingType/RateEdit.php
composer.json

See silverorange/swat#65
https://hippoeducation.tpondemand.com/entity/672

Update to use SwatDBDataobject::getAttributes()

---

Store/dataobjects/StoreAccountAddress.php
Store/dataobjects/StoreAddress.php

https://hippoeducation.tpondemand.com/entity/795

Getters and setters for address properties

---

Store/admin/components/Account/Index.php
Store/admin/components/Account/index.xml

https://hippoeducation.tpondemand.com/entity/942

Remove un-needed property

---

Store/admin/StoreOrderChart.php

allows StoreOrderChart to be extended

change access level of app and instance to protected 

---

Store/StoreOrderCommentDigestMailer.php

https://hippoeducation.tpondemand.com/entity/2944

Stop only variables should be passed by reference

---

Store/pages/StoreCheckoutPaymentMethodPage.php

I believe these changes should have happened along with https://github.com/silverorange/store/pull/126

Remove reference to a non-existent property

---

Store/pages/StoreCategoryPage.php
Store/pages/StoreNotVisiblePage.php
Store/pages/StoreProductImagePage.php
Store/pages/StoreProductPage.php

https://docs.google.com/spreadsheets/d/1xXfkvEoIt0vYAuojmmPj85SF-9oD1fj_vVCewHfs6K8/edit#gid=0

This method no longer takes a secure param

---

Store/StoreAuthorizeNetPaymentProvider.php
Store/exceptions/StorePaymentAuthorizeNetException.php

Used by https://github.com/silverorange/course-host/pull/1225

Use new Authorize.net APIs for payment processing.

---

Store/pages/StoreCheckoutConfirmationPage.php

https://app.clubhouse.io/silverorangeinc/story/10166/add-peds-em-attendance-flag-to-account

Allow for configurable account saving conditions

---

Store/Store.php
Store/StoreAnalyticsOrderTracker.php
composer.json

https://airtable.com/tblHi2RES2ktb1XG9/viw25F7lpg5VImzoa/rec0MKXoHi5LPzuD8?blocks=hide

Remove Friendbuy conversion support as PHP sites are no longer using it

---

Store/pages/StoreCheckoutConfirmationPage.php

refactor this a little to make more sense https://github.com/silverorange/store/pull/144

refactor a little

---

Store/Store.php
composer.json

Removes all mentions of akismet from store, allows version 12 of site in composer.json

Allow site version 12 in composer.json

---

Store/StoreApplication.php
Store/pages/StoreCheckoutThankYouPage.php
composer.json

Will require a major version update

Deprecate net notifier

---

Store/pages/StoreCheckoutConfirmationPage.php

Fixes issue restoring session account when order saving fails for signed in customers.

Fix order processing failure account restore

---

Jenkinsfile
Store/StoreFacebookConversionTracker.php

1. Checkout PR along with https://github.com/silverorange/course-host/pull/2021 using yarn with symlink `store`.
2. Use Meta pixel control panel: https://business.facebook.com/events_manager2/list/pixel/1564082923833222/test_events?business_id=1222653327818043
and under Kaitlyn Ackroyd's Pixel > Test... enter https://berna.silverorange.com/course-host-ccme/work-USERNAME/www into Test URL input.
3. Meta control panel with open new tab with your test URL to start navigating to test, and pixel activity appears under events received.
Before requesting review for this PR, make sure the following tasks are complete:
Before merging this PR, make sure the following tasks are complete:

FB to Meta Pixel Update to new API

---

Store/admin/components/SalesByRegionReport/Details.php
Store/admin/components/SalesByRegionReport/Index.php
Store/admin/components/SalesByRegionReport/details.xml
Store/admin/components/SalesByRegionReport/index.xml

Show taxes exactly like the shipping column. By default hidden.

Show tax column on Sales Report By Region report

---

Jenkinsfile
composer.json

Ran the following: 
```sh
composer require -Wm \
"silverorange/swat:^7.9.2" \
"silverorange/site:^15.3.2" \
"silverorange/admin:^7.0.3"
```
Add step-by-step instructions for testing the PR, if necessary.
1. Check out this PR.
2. Check static analysis / CI passes.
Before requesting review for this PR, make sure the following tasks are
complete:
Before merging this PR, make sure the following tasks are complete:

Bump dependency versions
